### ISSUE TITLE
Compatibility with the Epic Game Store

### ISSUE THREAD

**Issue by Flogis** [pvutov/WargameModManager#4]
Hi (yes me again),

Recently Wargame Red Dragon was released for free on the EGS. Problem, the Mod Manager works by launching Steam and backing up Steam profiles.
Is there a way to mitigate that issue somehow ? Or change a bit the current Mod Manager to work with the EGS ?

There are other ways to install mods so it's not a real issue, it's just that the Manager functions are very nice.

Cheers.

**Comment by pvutov** [comment]
It's not a big change, perhaps I'll take some time on the weekend to patch it in. The behavior can be easily extended by adjusting two lines (https://github.com/pvutov/WargameModManager/blob/master/WargameModManager/src/PathFinder.cs#L54). 

The main effort would be in looking up where EGS stores user profiles and in testing the change (since I myself use neither wargame with EGS nor the mod manager).  Steam's user profile folder can be found in the windows registry, not sure about EGS. If you have that info it will make things easier, if not then I'll look it up if/when I sit down with the issue.

**Comment by Flogis** [comment]
EGS stores the profile file at the same place as the replays. Located in C:\Users%username%\Saved Games\EugenSystems\WarGame3

The Manager seem to actually work for EGS, it replaced the NDF, but Eugen actually made only one folder with all the files for EGS. Using the Mod Manager might be more problematic because of that now (see below).
![image](https://user-images.githubusercontent.com/31567404/110173703-4acccb80-7dff-11eb-86e0-3156a913a9ef.png)

**Comment by pvutov** [comment]
Made some fixes for the profile stuff, try it out now.
https://github.com/pvutov/WargameModManager/releases

The config looks like this:
```
dir:H:\EpicLibrary\WargameRedDragon
manageprofiles:true
autoupdate:false
#steamprofiledir:C:\Program Files (x86)\Steam\userdata\
epicprofiledir:C:\Users\root\Saved Games\EugenSystems\WarGame3
```

I didn't put any thought into the problem of exchanging actual mod files. If you have a concrete suggestion for how you want it to work, tell me and I'll take a look. For now I think the current approach should be sufficient to support both versions - the manager just places the folders as you did, so if the two stores have a different layout, just place both layouts there and it will always do both patterns (one would then be pointless since the game isn't using it, but thats not a big deal).

You might also want to try the heuristic mode (read line 4 of https://github.com/pvutov/WargameModManager/blob/master/WargameModManager/PUBLISH_INSTRUCTIONS.txt)

**Comment by pvutov** [comment]
I assume this works for you, feel free to open a new issue if something else comes up.
